tabs to spaces everywhere

diff --git a/go_hummingbird b/go_hummingbird
--- a/go_hummingbird
+++ b/go_hummingbird
@@ -7,22 +7,22 @@ sudo echo "Go Hummingbird!"
 # Determine the network interface
 INTERFACE=$(echo $INTERFACE)
 if [[ -z "${INTERFACE}" ]]; then
-	if [[ "${OSTYPE}" == "linux-gnu" ]]; then
-		#INTERFACE=$(ip route get 8.8.8.8 | awk '{ print $(NF-2); exit }')
-		INTERFACE=$(ip route get 8.8.8.8 | cut -f5 -d' ' | head -1)
-	elif [[ "${OSTYPE}" == "darwin"* ]]; then
-		INTERFACE=$(route get 8.8.8.8 | grep interface | awk '{ print $NF; exit }')
-	else
-		echo "This script does not support this operating system. An override of INTERFACE is required."
-		exit 1
-	fi
-	export INTERFACE
+    if [[ "${OSTYPE}" == "linux-gnu" ]]; then
+        #INTERFACE=$(ip route get 8.8.8.8 | awk '{ print $(NF-2); exit }')
+        INTERFACE=$(ip route get 8.8.8.8 | cut -f5 -d' ' | head -1)
+    elif [[ "${OSTYPE}" == "darwin"* ]]; then
+        INTERFACE=$(route get 8.8.8.8 | grep interface | awk '{ print $NF; exit }')
+    else
+        echo "This script does not support this operating system. An override of INTERFACE is required."
+        exit 1
+    fi
+    export INTERFACE
 fi
 
 # Use Python version with pygame installed
 PYGAMEPYTHON=$(echo $PYGAMEPYTHON)
 if [[ -z "${PYGAMEPYTHON}" ]]; then
-	PYGAMEPYTHON="python"
+    PYGAMEPYTHON="python"
 fi
 
 # Pipe tcpdump output to Hummingbird
